foreground              #96A8BC
background              #1D2535
selection_foreground    #1D2535
selection_background    #4A86CC
cursor                  #E0DAC8
cursor_text_color       #1D2535
scrollbar_handle_color  #5E7088
scrollbar_track_color   #2A3448
url_color               #4A86CC
active_border_color     #4A86CC
inactive_border_color   #3D4F66
bell_border_color       #C8B07A
wayland_titlebar_color system
macos_titlebar_color system
active_tab_foreground   #151A24
active_tab_background   #4A86CC
inactive_tab_foreground #96A8BC
inactive_tab_background #2A3448
tab_bar_background      #151A24
mark1_foreground #1D2535
mark1_background #4A86CC
mark2_foreground #1D2535
mark2_background #A87088
mark3_foreground #1D2535
mark3_background #3AAC92
color0  #2A3448
color8  #3D4F66
color1  #A05252
color9  #A05252
color2  #5B7F59
color10 #5B7F59
color3  #C8B07A
color11 #C8B07A
color4  #4A86CC
color12 #4A86CC
color5  #A87088
color13 #A87088
color6  #3AAC92
color14 #3AAC92
color7  #96A8BC
color15 #E0DAC8
